/*
 * This file is generated by jOOQ.
 */
package tech.crom.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import tech.crom.db.tables.CommitDetailsTable;
import tech.crom.db.tables.CommitMetadataTable;
import tech.crom.db.tables.FlywaySchemaHistoryTable;
import tech.crom.db.tables.ProjectDetailTrackerTable;
import tech.crom.db.tables.ProjectDetailsTable;
import tech.crom.db.tables.RepoDetailsTable;
import tech.crom.db.tables.RepositoryTokensTable;
import tech.crom.db.tables.SecurityIdSeqTable;
import tech.crom.db.tables.UserDetailsTable;
import tech.crom.db.tables.UserTokensTable;
import tech.crom.db.tables.VersionBumpersTable;
import tech.crom.db.tables.VersionStateMachineConnectionsTable;
import tech.crom.db.tables.VersionStateMachineDefinitionsTable;
import tech.crom.db.tables.VersionStateMachineStatesTable;
import tech.crom.db.tables.WatcherTable;
import tech.crom.db.tables.records.CommitDetailsRecord;
import tech.crom.db.tables.records.CommitMetadataRecord;
import tech.crom.db.tables.records.FlywaySchemaHistoryRecord;
import tech.crom.db.tables.records.ProjectDetailTrackerRecord;
import tech.crom.db.tables.records.ProjectDetailsRecord;
import tech.crom.db.tables.records.RepoDetailsRecord;
import tech.crom.db.tables.records.RepositoryTokensRecord;
import tech.crom.db.tables.records.SecurityIdSeqRecord;
import tech.crom.db.tables.records.UserDetailsRecord;
import tech.crom.db.tables.records.UserTokensRecord;
import tech.crom.db.tables.records.VersionBumpersRecord;
import tech.crom.db.tables.records.VersionStateMachineConnectionsRecord;
import tech.crom.db.tables.records.VersionStateMachineDefinitionsRecord;
import tech.crom.db.tables.records.VersionStateMachineStatesRecord;
import tech.crom.db.tables.records.WatcherRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>version_manager_test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CommitDetailsRecord, Long> IDENTITY_COMMIT_DETAILS = Identities0.IDENTITY_COMMIT_DETAILS;
    public static final Identity<CommitMetadataRecord, Long> IDENTITY_COMMIT_METADATA = Identities0.IDENTITY_COMMIT_METADATA;
    public static final Identity<ProjectDetailTrackerRecord, Long> IDENTITY_PROJECT_DETAIL_TRACKER = Identities0.IDENTITY_PROJECT_DETAIL_TRACKER;
    public static final Identity<ProjectDetailsRecord, Long> IDENTITY_PROJECT_DETAILS = Identities0.IDENTITY_PROJECT_DETAILS;
    public static final Identity<RepoDetailsRecord, Long> IDENTITY_REPO_DETAILS = Identities0.IDENTITY_REPO_DETAILS;
    public static final Identity<RepositoryTokensRecord, Long> IDENTITY_REPOSITORY_TOKENS = Identities0.IDENTITY_REPOSITORY_TOKENS;
    public static final Identity<SecurityIdSeqRecord, Long> IDENTITY_SECURITY_ID_SEQ = Identities0.IDENTITY_SECURITY_ID_SEQ;
    public static final Identity<UserDetailsRecord, Long> IDENTITY_USER_DETAILS = Identities0.IDENTITY_USER_DETAILS;
    public static final Identity<UserTokensRecord, Long> IDENTITY_USER_TOKENS = Identities0.IDENTITY_USER_TOKENS;
    public static final Identity<VersionBumpersRecord, Long> IDENTITY_VERSION_BUMPERS = Identities0.IDENTITY_VERSION_BUMPERS;
    public static final Identity<VersionStateMachineConnectionsRecord, Long> IDENTITY_VERSION_STATE_MACHINE_CONNECTIONS = Identities0.IDENTITY_VERSION_STATE_MACHINE_CONNECTIONS;
    public static final Identity<VersionStateMachineDefinitionsRecord, Long> IDENTITY_VERSION_STATE_MACHINE_DEFINITIONS = Identities0.IDENTITY_VERSION_STATE_MACHINE_DEFINITIONS;
    public static final Identity<VersionStateMachineStatesRecord, Long> IDENTITY_VERSION_STATE_MACHINE_STATES = Identities0.IDENTITY_VERSION_STATE_MACHINE_STATES;
    public static final Identity<WatcherRecord, Long> IDENTITY_WATCHER = Identities0.IDENTITY_WATCHER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CommitDetailsRecord> KEY_COMMIT_DETAILS_PRIMARY = UniqueKeys0.KEY_COMMIT_DETAILS_PRIMARY;
    public static final UniqueKey<CommitMetadataRecord> KEY_COMMIT_METADATA_PRIMARY = UniqueKeys0.KEY_COMMIT_METADATA_PRIMARY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;
    public static final UniqueKey<ProjectDetailTrackerRecord> KEY_PROJECT_DETAIL_TRACKER_PRIMARY = UniqueKeys0.KEY_PROJECT_DETAIL_TRACKER_PRIMARY;
    public static final UniqueKey<ProjectDetailsRecord> KEY_PROJECT_DETAILS_PRIMARY = UniqueKeys0.KEY_PROJECT_DETAILS_PRIMARY;
    public static final UniqueKey<RepoDetailsRecord> KEY_REPO_DETAILS_PRIMARY = UniqueKeys0.KEY_REPO_DETAILS_PRIMARY;
    public static final UniqueKey<RepositoryTokensRecord> KEY_REPOSITORY_TOKENS_PRIMARY = UniqueKeys0.KEY_REPOSITORY_TOKENS_PRIMARY;
    public static final UniqueKey<RepositoryTokensRecord> KEY_REPOSITORY_TOKENS_PUBLIC_REPO_TOKEN = UniqueKeys0.KEY_REPOSITORY_TOKENS_PUBLIC_REPO_TOKEN;
    public static final UniqueKey<SecurityIdSeqRecord> KEY_SECURITY_ID_SEQ_PRIMARY = UniqueKeys0.KEY_SECURITY_ID_SEQ_PRIMARY;
    public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_PRIMARY = UniqueKeys0.KEY_USER_DETAILS_PRIMARY;
    public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PRIMARY = UniqueKeys0.KEY_USER_TOKENS_PRIMARY;
    public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PUBLIC_USER_TOKEN = UniqueKeys0.KEY_USER_TOKENS_PUBLIC_USER_TOKEN;
    public static final UniqueKey<VersionBumpersRecord> KEY_VERSION_BUMPERS_PRIMARY = UniqueKeys0.KEY_VERSION_BUMPERS_PRIMARY;
    public static final UniqueKey<VersionStateMachineConnectionsRecord> KEY_VERSION_STATE_MACHINE_CONNECTIONS_PRIMARY = UniqueKeys0.KEY_VERSION_STATE_MACHINE_CONNECTIONS_PRIMARY;
    public static final UniqueKey<VersionStateMachineConnectionsRecord> KEY_VERSION_STATE_MACHINE_CONNECTIONS_SOURCE = UniqueKeys0.KEY_VERSION_STATE_MACHINE_CONNECTIONS_SOURCE;
    public static final UniqueKey<VersionStateMachineDefinitionsRecord> KEY_VERSION_STATE_MACHINE_DEFINITIONS_PRIMARY = UniqueKeys0.KEY_VERSION_STATE_MACHINE_DEFINITIONS_PRIMARY;
    public static final UniqueKey<VersionStateMachineDefinitionsRecord> KEY_VERSION_STATE_MACHINE_DEFINITIONS_REPO_DETAIL_ID = UniqueKeys0.KEY_VERSION_STATE_MACHINE_DEFINITIONS_REPO_DETAIL_ID;
    public static final UniqueKey<VersionStateMachineStatesRecord> KEY_VERSION_STATE_MACHINE_STATES_PRIMARY = UniqueKeys0.KEY_VERSION_STATE_MACHINE_STATES_PRIMARY;
    public static final UniqueKey<VersionStateMachineStatesRecord> KEY_VERSION_STATE_MACHINE_STATES_VERSION_STATE_MACHINE_ID = UniqueKeys0.KEY_VERSION_STATE_MACHINE_STATES_VERSION_STATE_MACHINE_ID;
    public static final UniqueKey<WatcherRecord> KEY_WATCHER_PRIMARY = UniqueKeys0.KEY_WATCHER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CommitDetailsRecord, RepoDetailsRecord> COMMIT_DETAILS_IBFK_1 = ForeignKeys0.COMMIT_DETAILS_IBFK_1;
    public static final ForeignKey<CommitDetailsRecord, CommitDetailsRecord> COMMIT_DETAILS_IBFK_2 = ForeignKeys0.COMMIT_DETAILS_IBFK_2;
    public static final ForeignKey<CommitMetadataRecord, CommitDetailsRecord> COMMIT_METADATA_IBFK_1 = ForeignKeys0.COMMIT_METADATA_IBFK_1;
    public static final ForeignKey<CommitMetadataRecord, ProjectDetailsRecord> COMMIT_METADATA_IBFK_2 = ForeignKeys0.COMMIT_METADATA_IBFK_2;
    public static final ForeignKey<CommitMetadataRecord, RepoDetailsRecord> COMMIT_METADATA_IBFK_3 = ForeignKeys0.COMMIT_METADATA_IBFK_3;
    public static final ForeignKey<ProjectDetailTrackerRecord, ProjectDetailsRecord> PROJECT_DETAIL_TRACKER_IBFK_1 = ForeignKeys0.PROJECT_DETAIL_TRACKER_IBFK_1;
    public static final ForeignKey<ProjectDetailTrackerRecord, UserDetailsRecord> PROJECT_DETAIL_TRACKER_IBFK_2 = ForeignKeys0.PROJECT_DETAIL_TRACKER_IBFK_2;
    public static final ForeignKey<ProjectDetailsRecord, SecurityIdSeqRecord> PROJECT_DETAILS_IBFK_1 = ForeignKeys0.PROJECT_DETAILS_IBFK_1;
    public static final ForeignKey<RepoDetailsRecord, ProjectDetailsRecord> REPO_DETAILS_IBFK_1 = ForeignKeys0.REPO_DETAILS_IBFK_1;
    public static final ForeignKey<RepoDetailsRecord, VersionBumpersRecord> REPO_DETAILS_IBFK_2 = ForeignKeys0.REPO_DETAILS_IBFK_2;
    public static final ForeignKey<RepoDetailsRecord, SecurityIdSeqRecord> REPO_DETAILS_IBFK_3 = ForeignKeys0.REPO_DETAILS_IBFK_3;
    public static final ForeignKey<RepositoryTokensRecord, RepoDetailsRecord> REPOSITORY_TOKENS_IBFK_1 = ForeignKeys0.REPOSITORY_TOKENS_IBFK_1;
    public static final ForeignKey<UserTokensRecord, UserDetailsRecord> USER_TOKENS_IBFK_1 = ForeignKeys0.USER_TOKENS_IBFK_1;
    public static final ForeignKey<VersionStateMachineConnectionsRecord, VersionStateMachineDefinitionsRecord> VERSION_STATE_MACHINE_CONNECTIONS_IBFK_1 = ForeignKeys0.VERSION_STATE_MACHINE_CONNECTIONS_IBFK_1;
    public static final ForeignKey<VersionStateMachineConnectionsRecord, VersionStateMachineStatesRecord> VERSION_STATE_MACHINE_CONNECTIONS_IBFK_2 = ForeignKeys0.VERSION_STATE_MACHINE_CONNECTIONS_IBFK_2;
    public static final ForeignKey<VersionStateMachineConnectionsRecord, VersionStateMachineStatesRecord> VERSION_STATE_MACHINE_CONNECTIONS_IBFK_3 = ForeignKeys0.VERSION_STATE_MACHINE_CONNECTIONS_IBFK_3;
    public static final ForeignKey<VersionStateMachineDefinitionsRecord, RepoDetailsRecord> VERSION_STATE_MACHINE_DEFINITIONS_IBFK_1 = ForeignKeys0.VERSION_STATE_MACHINE_DEFINITIONS_IBFK_1;
    public static final ForeignKey<VersionStateMachineStatesRecord, VersionStateMachineDefinitionsRecord> VERSION_STATE_MACHINE_STATES_IBFK_1 = ForeignKeys0.VERSION_STATE_MACHINE_STATES_IBFK_1;
    public static final ForeignKey<WatcherRecord, UserDetailsRecord> WATCHER_IBFK_1 = ForeignKeys0.WATCHER_IBFK_1;
    public static final ForeignKey<WatcherRecord, ProjectDetailsRecord> WATCHER_IBFK_2 = ForeignKeys0.WATCHER_IBFK_2;
    public static final ForeignKey<WatcherRecord, RepoDetailsRecord> WATCHER_IBFK_3 = ForeignKeys0.WATCHER_IBFK_3;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CommitDetailsRecord, Long> IDENTITY_COMMIT_DETAILS = Internal.createIdentity(CommitDetailsTable.COMMIT_DETAILS, CommitDetailsTable.COMMIT_DETAILS.COMMIT_DETAIL_ID);
        public static Identity<CommitMetadataRecord, Long> IDENTITY_COMMIT_METADATA = Internal.createIdentity(CommitMetadataTable.COMMIT_METADATA, CommitMetadataTable.COMMIT_METADATA.COMMIT_METADATA_ID);
        public static Identity<ProjectDetailTrackerRecord, Long> IDENTITY_PROJECT_DETAIL_TRACKER = Internal.createIdentity(ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER, ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER.PROJECT_DETAIL_TRACKER_ID);
        public static Identity<ProjectDetailsRecord, Long> IDENTITY_PROJECT_DETAILS = Internal.createIdentity(ProjectDetailsTable.PROJECT_DETAILS, ProjectDetailsTable.PROJECT_DETAILS.PRODUCT_DETAIL_ID);
        public static Identity<RepoDetailsRecord, Long> IDENTITY_REPO_DETAILS = Internal.createIdentity(RepoDetailsTable.REPO_DETAILS, RepoDetailsTable.REPO_DETAILS.REPO_DETAIL_ID);
        public static Identity<RepositoryTokensRecord, Long> IDENTITY_REPOSITORY_TOKENS = Internal.createIdentity(RepositoryTokensTable.REPOSITORY_TOKENS, RepositoryTokensTable.REPOSITORY_TOKENS.REPOSITORY_TOKEN_ID);
        public static Identity<SecurityIdSeqRecord, Long> IDENTITY_SECURITY_ID_SEQ = Internal.createIdentity(SecurityIdSeqTable.SECURITY_ID_SEQ, SecurityIdSeqTable.SECURITY_ID_SEQ.SECURITY_ID);
        public static Identity<UserDetailsRecord, Long> IDENTITY_USER_DETAILS = Internal.createIdentity(UserDetailsTable.USER_DETAILS, UserDetailsTable.USER_DETAILS.USER_ID);
        public static Identity<UserTokensRecord, Long> IDENTITY_USER_TOKENS = Internal.createIdentity(UserTokensTable.USER_TOKENS, UserTokensTable.USER_TOKENS.USER_TOKEN_ID);
        public static Identity<VersionBumpersRecord, Long> IDENTITY_VERSION_BUMPERS = Internal.createIdentity(VersionBumpersTable.VERSION_BUMPERS, VersionBumpersTable.VERSION_BUMPERS.VERSION_BUMPER_ID);
        public static Identity<VersionStateMachineConnectionsRecord, Long> IDENTITY_VERSION_STATE_MACHINE_CONNECTIONS = Internal.createIdentity(VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS, VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS.STATE_MACHINE_DETAIL_ID);
        public static Identity<VersionStateMachineDefinitionsRecord, Long> IDENTITY_VERSION_STATE_MACHINE_DEFINITIONS = Internal.createIdentity(VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS, VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS.VERSION_STATE_MACHINE_ID);
        public static Identity<VersionStateMachineStatesRecord, Long> IDENTITY_VERSION_STATE_MACHINE_STATES = Internal.createIdentity(VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES, VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES.VERSION_STATE_MACHINE_STATE_ID);
        public static Identity<WatcherRecord, Long> IDENTITY_WATCHER = Internal.createIdentity(WatcherTable.WATCHER, WatcherTable.WATCHER.WATCHER_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CommitDetailsRecord> KEY_COMMIT_DETAILS_PRIMARY = Internal.createUniqueKey(CommitDetailsTable.COMMIT_DETAILS, "KEY_commit_details_PRIMARY", CommitDetailsTable.COMMIT_DETAILS.COMMIT_DETAIL_ID);
        public static final UniqueKey<CommitMetadataRecord> KEY_COMMIT_METADATA_PRIMARY = Internal.createUniqueKey(CommitMetadataTable.COMMIT_METADATA, "KEY_commit_metadata_PRIMARY", CommitMetadataTable.COMMIT_METADATA.COMMIT_METADATA_ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<ProjectDetailTrackerRecord> KEY_PROJECT_DETAIL_TRACKER_PRIMARY = Internal.createUniqueKey(ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER, "KEY_project_detail_tracker_PRIMARY", ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER.PROJECT_DETAIL_TRACKER_ID);
        public static final UniqueKey<ProjectDetailsRecord> KEY_PROJECT_DETAILS_PRIMARY = Internal.createUniqueKey(ProjectDetailsTable.PROJECT_DETAILS, "KEY_project_details_PRIMARY", ProjectDetailsTable.PROJECT_DETAILS.PRODUCT_DETAIL_ID);
        public static final UniqueKey<RepoDetailsRecord> KEY_REPO_DETAILS_PRIMARY = Internal.createUniqueKey(RepoDetailsTable.REPO_DETAILS, "KEY_repo_details_PRIMARY", RepoDetailsTable.REPO_DETAILS.REPO_DETAIL_ID);
        public static final UniqueKey<RepositoryTokensRecord> KEY_REPOSITORY_TOKENS_PRIMARY = Internal.createUniqueKey(RepositoryTokensTable.REPOSITORY_TOKENS, "KEY_repository_tokens_PRIMARY", RepositoryTokensTable.REPOSITORY_TOKENS.REPOSITORY_TOKEN_ID);
        public static final UniqueKey<RepositoryTokensRecord> KEY_REPOSITORY_TOKENS_PUBLIC_REPO_TOKEN = Internal.createUniqueKey(RepositoryTokensTable.REPOSITORY_TOKENS, "KEY_repository_tokens_public_repo_token", RepositoryTokensTable.REPOSITORY_TOKENS.PUBLIC_REPO_TOKEN);
        public static final UniqueKey<SecurityIdSeqRecord> KEY_SECURITY_ID_SEQ_PRIMARY = Internal.createUniqueKey(SecurityIdSeqTable.SECURITY_ID_SEQ, "KEY_security_id_seq_PRIMARY", SecurityIdSeqTable.SECURITY_ID_SEQ.SECURITY_ID);
        public static final UniqueKey<UserDetailsRecord> KEY_USER_DETAILS_PRIMARY = Internal.createUniqueKey(UserDetailsTable.USER_DETAILS, "KEY_user_details_PRIMARY", UserDetailsTable.USER_DETAILS.USER_ID);
        public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PRIMARY = Internal.createUniqueKey(UserTokensTable.USER_TOKENS, "KEY_user_tokens_PRIMARY", UserTokensTable.USER_TOKENS.USER_TOKEN_ID);
        public static final UniqueKey<UserTokensRecord> KEY_USER_TOKENS_PUBLIC_USER_TOKEN = Internal.createUniqueKey(UserTokensTable.USER_TOKENS, "KEY_user_tokens_public_user_token", UserTokensTable.USER_TOKENS.PUBLIC_USER_TOKEN);
        public static final UniqueKey<VersionBumpersRecord> KEY_VERSION_BUMPERS_PRIMARY = Internal.createUniqueKey(VersionBumpersTable.VERSION_BUMPERS, "KEY_version_bumpers_PRIMARY", VersionBumpersTable.VERSION_BUMPERS.VERSION_BUMPER_ID);
        public static final UniqueKey<VersionStateMachineConnectionsRecord> KEY_VERSION_STATE_MACHINE_CONNECTIONS_PRIMARY = Internal.createUniqueKey(VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS, "KEY_version_state_machine_connections_PRIMARY", VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS.STATE_MACHINE_DETAIL_ID);
        public static final UniqueKey<VersionStateMachineConnectionsRecord> KEY_VERSION_STATE_MACHINE_CONNECTIONS_SOURCE = Internal.createUniqueKey(VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS, "KEY_version_state_machine_connections_source", VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS.SOURCE, VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS.DESTINATION);
        public static final UniqueKey<VersionStateMachineDefinitionsRecord> KEY_VERSION_STATE_MACHINE_DEFINITIONS_PRIMARY = Internal.createUniqueKey(VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS, "KEY_version_state_machine_definitions_PRIMARY", VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS.VERSION_STATE_MACHINE_ID);
        public static final UniqueKey<VersionStateMachineDefinitionsRecord> KEY_VERSION_STATE_MACHINE_DEFINITIONS_REPO_DETAIL_ID = Internal.createUniqueKey(VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS, "KEY_version_state_machine_definitions_repo_detail_id", VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS.REPO_DETAIL_ID);
        public static final UniqueKey<VersionStateMachineStatesRecord> KEY_VERSION_STATE_MACHINE_STATES_PRIMARY = Internal.createUniqueKey(VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES, "KEY_version_state_machine_states_PRIMARY", VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES.VERSION_STATE_MACHINE_STATE_ID);
        public static final UniqueKey<VersionStateMachineStatesRecord> KEY_VERSION_STATE_MACHINE_STATES_VERSION_STATE_MACHINE_ID = Internal.createUniqueKey(VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES, "KEY_version_state_machine_states_version_state_machine_id", VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES.VERSION_STATE_MACHINE_ID, VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES.STATE_NAME);
        public static final UniqueKey<WatcherRecord> KEY_WATCHER_PRIMARY = Internal.createUniqueKey(WatcherTable.WATCHER, "KEY_watcher_PRIMARY", WatcherTable.WATCHER.WATCHER_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CommitDetailsRecord, RepoDetailsRecord> COMMIT_DETAILS_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_REPO_DETAILS_PRIMARY, CommitDetailsTable.COMMIT_DETAILS, "commit_details_ibfk_1", CommitDetailsTable.COMMIT_DETAILS.REPO_DETAIL_ID);
        public static final ForeignKey<CommitDetailsRecord, CommitDetailsRecord> COMMIT_DETAILS_IBFK_2 = Internal.createForeignKey(tech.crom.db.Keys.KEY_COMMIT_DETAILS_PRIMARY, CommitDetailsTable.COMMIT_DETAILS, "commit_details_ibfk_2", CommitDetailsTable.COMMIT_DETAILS.PARENT_COMMIT_ID);
        public static final ForeignKey<CommitMetadataRecord, CommitDetailsRecord> COMMIT_METADATA_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_COMMIT_DETAILS_PRIMARY, CommitMetadataTable.COMMIT_METADATA, "commit_metadata_ibfk_1", CommitMetadataTable.COMMIT_METADATA.COMMIT_ID);
        public static final ForeignKey<CommitMetadataRecord, ProjectDetailsRecord> COMMIT_METADATA_IBFK_2 = Internal.createForeignKey(tech.crom.db.Keys.KEY_PROJECT_DETAILS_PRIMARY, CommitMetadataTable.COMMIT_METADATA, "commit_metadata_ibfk_2", CommitMetadataTable.COMMIT_METADATA.PROJECT_ID);
        public static final ForeignKey<CommitMetadataRecord, RepoDetailsRecord> COMMIT_METADATA_IBFK_3 = Internal.createForeignKey(tech.crom.db.Keys.KEY_REPO_DETAILS_PRIMARY, CommitMetadataTable.COMMIT_METADATA, "commit_metadata_ibfk_3", CommitMetadataTable.COMMIT_METADATA.REPO_ID);
        public static final ForeignKey<ProjectDetailTrackerRecord, ProjectDetailsRecord> PROJECT_DETAIL_TRACKER_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_PROJECT_DETAILS_PRIMARY, ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER, "project_detail_tracker_ibfk_1", ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER.PRODUCT_DETAIL_ID);
        public static final ForeignKey<ProjectDetailTrackerRecord, UserDetailsRecord> PROJECT_DETAIL_TRACKER_IBFK_2 = Internal.createForeignKey(tech.crom.db.Keys.KEY_USER_DETAILS_PRIMARY, ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER, "project_detail_tracker_ibfk_2", ProjectDetailTrackerTable.PROJECT_DETAIL_TRACKER.USER_ID);
        public static final ForeignKey<ProjectDetailsRecord, SecurityIdSeqRecord> PROJECT_DETAILS_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_SECURITY_ID_SEQ_PRIMARY, ProjectDetailsTable.PROJECT_DETAILS, "project_details_ibfk_1", ProjectDetailsTable.PROJECT_DETAILS.SECURITY_ID);
        public static final ForeignKey<RepoDetailsRecord, ProjectDetailsRecord> REPO_DETAILS_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_PROJECT_DETAILS_PRIMARY, RepoDetailsTable.REPO_DETAILS, "repo_details_ibfk_1", RepoDetailsTable.REPO_DETAILS.PROJECT_ID);
        public static final ForeignKey<RepoDetailsRecord, VersionBumpersRecord> REPO_DETAILS_IBFK_2 = Internal.createForeignKey(tech.crom.db.Keys.KEY_VERSION_BUMPERS_PRIMARY, RepoDetailsTable.REPO_DETAILS, "repo_details_ibfk_2", RepoDetailsTable.REPO_DETAILS.VERSION_BUMPER_ID);
        public static final ForeignKey<RepoDetailsRecord, SecurityIdSeqRecord> REPO_DETAILS_IBFK_3 = Internal.createForeignKey(tech.crom.db.Keys.KEY_SECURITY_ID_SEQ_PRIMARY, RepoDetailsTable.REPO_DETAILS, "repo_details_ibfk_3", RepoDetailsTable.REPO_DETAILS.SECURITY_ID);
        public static final ForeignKey<RepositoryTokensRecord, RepoDetailsRecord> REPOSITORY_TOKENS_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_REPO_DETAILS_PRIMARY, RepositoryTokensTable.REPOSITORY_TOKENS, "repository_tokens_ibfk_1", RepositoryTokensTable.REPOSITORY_TOKENS.REPO_ID);
        public static final ForeignKey<UserTokensRecord, UserDetailsRecord> USER_TOKENS_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_USER_DETAILS_PRIMARY, UserTokensTable.USER_TOKENS, "user_tokens_ibfk_1", UserTokensTable.USER_TOKENS.USER_ID);
        public static final ForeignKey<VersionStateMachineConnectionsRecord, VersionStateMachineDefinitionsRecord> VERSION_STATE_MACHINE_CONNECTIONS_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_VERSION_STATE_MACHINE_DEFINITIONS_PRIMARY, VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS, "version_state_machine_connections_ibfk_1", VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS.VERSION_STATE_MACHINE_ID);
        public static final ForeignKey<VersionStateMachineConnectionsRecord, VersionStateMachineStatesRecord> VERSION_STATE_MACHINE_CONNECTIONS_IBFK_2 = Internal.createForeignKey(tech.crom.db.Keys.KEY_VERSION_STATE_MACHINE_STATES_PRIMARY, VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS, "version_state_machine_connections_ibfk_2", VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS.SOURCE);
        public static final ForeignKey<VersionStateMachineConnectionsRecord, VersionStateMachineStatesRecord> VERSION_STATE_MACHINE_CONNECTIONS_IBFK_3 = Internal.createForeignKey(tech.crom.db.Keys.KEY_VERSION_STATE_MACHINE_STATES_PRIMARY, VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS, "version_state_machine_connections_ibfk_3", VersionStateMachineConnectionsTable.VERSION_STATE_MACHINE_CONNECTIONS.DESTINATION);
        public static final ForeignKey<VersionStateMachineDefinitionsRecord, RepoDetailsRecord> VERSION_STATE_MACHINE_DEFINITIONS_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_REPO_DETAILS_PRIMARY, VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS, "version_state_machine_definitions_ibfk_1", VersionStateMachineDefinitionsTable.VERSION_STATE_MACHINE_DEFINITIONS.REPO_DETAIL_ID);
        public static final ForeignKey<VersionStateMachineStatesRecord, VersionStateMachineDefinitionsRecord> VERSION_STATE_MACHINE_STATES_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_VERSION_STATE_MACHINE_DEFINITIONS_PRIMARY, VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES, "version_state_machine_states_ibfk_1", VersionStateMachineStatesTable.VERSION_STATE_MACHINE_STATES.VERSION_STATE_MACHINE_ID);
        public static final ForeignKey<WatcherRecord, UserDetailsRecord> WATCHER_IBFK_1 = Internal.createForeignKey(tech.crom.db.Keys.KEY_USER_DETAILS_PRIMARY, WatcherTable.WATCHER, "watcher_ibfk_1", WatcherTable.WATCHER.USER_ID);
        public static final ForeignKey<WatcherRecord, ProjectDetailsRecord> WATCHER_IBFK_2 = Internal.createForeignKey(tech.crom.db.Keys.KEY_PROJECT_DETAILS_PRIMARY, WatcherTable.WATCHER, "watcher_ibfk_2", WatcherTable.WATCHER.PROJECT_DETAIL_ID);
        public static final ForeignKey<WatcherRecord, RepoDetailsRecord> WATCHER_IBFK_3 = Internal.createForeignKey(tech.crom.db.Keys.KEY_REPO_DETAILS_PRIMARY, WatcherTable.WATCHER, "watcher_ibfk_3", WatcherTable.WATCHER.REPO_DETAIL_ID);
    }
}
