/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.records;


import io.ehdev.conrad.db.tables.ProjectDetailsTable;

import java.util.UUID;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "project_details", schema = "public")
public class ProjectDetailsRecord extends UpdatableRecordImpl<ProjectDetailsRecord> implements Record2<UUID, String> {

	private static final long serialVersionUID = -1139705782;

	/**
	 * Setter for <code>public.project_details.uuid</code>.
	 */
	public void setUuid(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.project_details.uuid</code>.
	 */
	@Id
	@Column(name = "uuid", unique = true, nullable = false)
	@NotNull
	public UUID getUuid() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.project_details.project_name</code>.
	 */
	public void setProjectName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.project_details.project_name</code>.
	 */
	@Column(name = "project_name", unique = true, nullable = false, length = 255)
	@NotNull
	@Size(max = 255)
	public String getProjectName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UUID> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<UUID, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<UUID, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return ProjectDetailsTable.PROJECT_DETAILS.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ProjectDetailsTable.PROJECT_DETAILS.PROJECT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getProjectName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectDetailsRecord value1(UUID value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectDetailsRecord value2(String value) {
		setProjectName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProjectDetailsRecord values(UUID value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProjectDetailsRecord
	 */
	public ProjectDetailsRecord() {
		super(ProjectDetailsTable.PROJECT_DETAILS);
	}

	/**
	 * Create a detached, initialised ProjectDetailsRecord
	 */
	public ProjectDetailsRecord(UUID uuid, String projectName) {
		super(ProjectDetailsTable.PROJECT_DETAILS);

		setValue(0, uuid);
		setValue(1, projectName);
	}
}
