/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.records;


import io.ehdev.conrad.db.tables.RepoDetailsTable;

import java.util.UUID;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "repo_details", schema = "public")
public class RepoDetailsRecord extends UpdatableRecordImpl<RepoDetailsRecord> implements Record7<UUID, String, UUID, UUID, String, String, Boolean> {

    private static final long serialVersionUID = 1549391390;

    /**
     * Setter for <code>public.repo_details.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.repo_details.uuid</code>.
     */
    @Id
    @Column(name = "uuid", unique = true, nullable = false)
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.repo_details.repo_name</code>.
     */
    public void setRepoName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.repo_details.repo_name</code>.
     */
    @Column(name = "repo_name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getRepoName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.repo_details.project_uuid</code>.
     */
    public void setProjectUuid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.repo_details.project_uuid</code>.
     */
    @Column(name = "project_uuid")
    public UUID getProjectUuid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.repo_details.version_bumper_uuid</code>.
     */
    public void setVersionBumperUuid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.repo_details.version_bumper_uuid</code>.
     */
    @Column(name = "version_bumper_uuid")
    public UUID getVersionBumperUuid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.repo_details.url</code>.
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.repo_details.url</code>.
     */
    @Column(name = "url", length = 1024)
    @Size(max = 1024)
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.repo_details.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.repo_details.description</code>.
     */
    @Column(name = "description", nullable = false)
    @NotNull
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.repo_details.public</code>.
     */
    public void setPublic(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.repo_details.public</code>.
     */
    @Column(name = "public")
    public Boolean getPublic() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, UUID, UUID, String, String, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, String, UUID, UUID, String, String, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return RepoDetailsTable.REPO_DETAILS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RepoDetailsTable.REPO_DETAILS.REPO_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field3() {
        return RepoDetailsTable.REPO_DETAILS.PROJECT_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return RepoDetailsTable.REPO_DETAILS.VERSION_BUMPER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RepoDetailsTable.REPO_DETAILS.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return RepoDetailsTable.REPO_DETAILS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return RepoDetailsTable.REPO_DETAILS.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRepoName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value3() {
        return getProjectUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getVersionBumperUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getPublic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord value2(String value) {
        setRepoName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord value3(UUID value) {
        setProjectUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord value4(UUID value) {
        setVersionBumperUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord value5(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord value7(Boolean value) {
        setPublic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepoDetailsRecord values(UUID value1, String value2, UUID value3, UUID value4, String value5, String value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RepoDetailsRecord
     */
    public RepoDetailsRecord() {
        super(RepoDetailsTable.REPO_DETAILS);
    }

    /**
     * Create a detached, initialised RepoDetailsRecord
     */
    public RepoDetailsRecord(UUID uuid, String repoName, UUID projectUuid, UUID versionBumperUuid, String url, String description, Boolean public_) {
        super(RepoDetailsTable.REPO_DETAILS);

        set(0, uuid);
        set(1, repoName);
        set(2, projectUuid);
        set(3, versionBumperUuid);
        set(4, url);
        set(5, description);
        set(6, public_);
    }
}
