/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.records;


import io.ehdev.conrad.db.enums.TokenType;
import io.ehdev.conrad.db.tables.TokenAuthenticationsTable;

import java.time.Instant;
import java.util.UUID;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "token_authentications", schema = "public")
public class TokenAuthenticationsRecord extends UpdatableRecordImpl<TokenAuthenticationsRecord> implements Record5<UUID, Instant, Instant, Boolean, TokenType> {

    private static final long serialVersionUID = 749133999;

    /**
     * Setter for <code>public.token_authentications.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.token_authentications.uuid</code>.
     */
    @Id
    @Column(name = "uuid", unique = true, nullable = false)
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.token_authentications.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.token_authentications.created_at</code>.
     */
    @Column(name = "created_at", nullable = false)
    public Instant getCreatedAt() {
        return (Instant) get(1);
    }

    /**
     * Setter for <code>public.token_authentications.expires_at</code>.
     */
    public void setExpiresAt(Instant value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.token_authentications.expires_at</code>.
     */
    @Column(name = "expires_at")
    public Instant getExpiresAt() {
        return (Instant) get(2);
    }

    /**
     * Setter for <code>public.token_authentications.valid</code>.
     */
    public void setValid(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.token_authentications.valid</code>.
     */
    @Column(name = "valid")
    public Boolean getValid() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.token_authentications.token_type</code>.
     */
    public void setTokenType(TokenType value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.token_authentications.token_type</code>.
     */
    @Column(name = "token_type", nullable = false)
    @NotNull
    public TokenType getTokenType() {
        return (TokenType) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, Instant, Instant, Boolean, TokenType> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, Instant, Instant, Boolean, TokenType> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Instant> field2() {
        return TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Instant> field3() {
        return TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS.EXPIRES_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS.VALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TokenType> field5() {
        return TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS.TOKEN_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Instant value2() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Instant value3() {
        return getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenType value5() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenAuthenticationsRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenAuthenticationsRecord value2(Instant value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenAuthenticationsRecord value3(Instant value) {
        setExpiresAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenAuthenticationsRecord value4(Boolean value) {
        setValid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenAuthenticationsRecord value5(TokenType value) {
        setTokenType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenAuthenticationsRecord values(UUID value1, Instant value2, Instant value3, Boolean value4, TokenType value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenAuthenticationsRecord
     */
    public TokenAuthenticationsRecord() {
        super(TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS);
    }

    /**
     * Create a detached, initialised TokenAuthenticationsRecord
     */
    public TokenAuthenticationsRecord(UUID uuid, Instant createdAt, Instant expiresAt, Boolean valid, TokenType tokenType) {
        super(TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS);

        set(0, uuid);
        set(1, createdAt);
        set(2, expiresAt);
        set(3, valid);
        set(4, tokenType);
    }
}
