/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.records;


import io.ehdev.conrad.db.tables.UserPermissionsTable;

import java.util.UUID;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user_permissions", schema = "public", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"project_name", "repo_name"}),
	@UniqueConstraint(columnNames = {"project_uuid", "repo_details_uuid", "user_uuid"})
})
public class UserPermissionsRecord extends UpdatableRecordImpl<UserPermissionsRecord> implements Record7<UUID, String, String, UUID, UUID, UUID, Integer> {

	private static final long serialVersionUID = -2086424847;

	/**
	 * Setter for <code>public.user_permissions.uuid</code>.
	 */
	public void setUuid(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user_permissions.uuid</code>.
	 */
	@Id
	@Column(name = "uuid", unique = true, nullable = false)
	@NotNull
	public UUID getUuid() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.user_permissions.project_name</code>.
	 */
	public void setProjectName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user_permissions.project_name</code>.
	 */
	@Column(name = "project_name", nullable = false, length = 255)
	@NotNull
	@Size(max = 255)
	public String getProjectName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.user_permissions.repo_name</code>.
	 */
	public void setRepoName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.user_permissions.repo_name</code>.
	 */
	@Column(name = "repo_name", length = 255)
	@Size(max = 255)
	public String getRepoName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.user_permissions.project_uuid</code>.
	 */
	public void setProjectUuid(UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.user_permissions.project_uuid</code>.
	 */
	@Column(name = "project_uuid", nullable = false)
	@NotNull
	public UUID getProjectUuid() {
		return (UUID) getValue(3);
	}

	/**
	 * Setter for <code>public.user_permissions.repo_details_uuid</code>.
	 */
	public void setRepoDetailsUuid(UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.user_permissions.repo_details_uuid</code>.
	 */
	@Column(name = "repo_details_uuid")
	public UUID getRepoDetailsUuid() {
		return (UUID) getValue(4);
	}

	/**
	 * Setter for <code>public.user_permissions.user_uuid</code>.
	 */
	public void setUserUuid(UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.user_permissions.user_uuid</code>.
	 */
	@Column(name = "user_uuid", nullable = false)
	@NotNull
	public UUID getUserUuid() {
		return (UUID) getValue(5);
	}

	/**
	 * Setter for <code>public.user_permissions.permissions</code>.
	 */
	public void setPermissions(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.user_permissions.permissions</code>.
	 */
	@Column(name = "permissions", nullable = false, precision = 32)
	@NotNull
	public Integer getPermissions() {
		return (Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UUID> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<UUID, String, String, UUID, UUID, UUID, Integer> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<UUID, String, String, UUID, UUID, UUID, Integer> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return UserPermissionsTable.USER_PERMISSIONS.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return UserPermissionsTable.USER_PERMISSIONS.PROJECT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return UserPermissionsTable.USER_PERMISSIONS.REPO_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field4() {
		return UserPermissionsTable.USER_PERMISSIONS.PROJECT_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field5() {
		return UserPermissionsTable.USER_PERMISSIONS.REPO_DETAILS_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field6() {
		return UserPermissionsTable.USER_PERMISSIONS.USER_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return UserPermissionsTable.USER_PERMISSIONS.PERMISSIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getProjectName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getRepoName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value4() {
		return getProjectUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value5() {
		return getRepoDetailsUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value6() {
		return getUserUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getPermissions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord value1(UUID value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord value2(String value) {
		setProjectName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord value3(String value) {
		setRepoName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord value4(UUID value) {
		setProjectUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord value5(UUID value) {
		setRepoDetailsUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord value6(UUID value) {
		setUserUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord value7(Integer value) {
		setPermissions(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserPermissionsRecord values(UUID value1, String value2, String value3, UUID value4, UUID value5, UUID value6, Integer value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserPermissionsRecord
	 */
	public UserPermissionsRecord() {
		super(UserPermissionsTable.USER_PERMISSIONS);
	}

	/**
	 * Create a detached, initialised UserPermissionsRecord
	 */
	public UserPermissionsRecord(UUID uuid, String projectName, String repoName, UUID projectUuid, UUID repoDetailsUuid, UUID userUuid, Integer permissions) {
		super(UserPermissionsTable.USER_PERMISSIONS);

		setValue(0, uuid);
		setValue(1, projectName);
		setValue(2, repoName);
		setValue(3, projectUuid);
		setValue(4, repoDetailsUuid);
		setValue(5, userUuid);
		setValue(6, permissions);
	}
}
