version: 2
jobs:
  build:
    working_directory: ~/checkout
    docker:
      - image: ethankhall/merged-docker-build-platform:sha256:e5807378d6a4e4c83aaee13d95a69079265a7802250463fff8fedacbbcf51a71

      - image: mysql:latest
        environment:
          no_proxy: "*.local, 169.254/16"
          PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          GOSU_VERSION: 1.7
          MYSQL_MAJOR: 5.7
          MYSQL_VERSION: 5.7.17-1debian8
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: version_manager_test


    steps:
      - run:
          name: start ssh
          command: ssh-agent

      - add_ssh_keys:
          fingerprints:
            - "57:92:aa:e8:2b:e7:bf:3c:ff:fb:f2:ce:4f:c7:9c:82"

      - checkout

      - restore_cache:
          key: crom-{{ .Branch }}

      - run:
          name: Update Cache
          command: ./gradlew resolveDependencies

      - save_cache:
          key: crom-{{ .Branch }}
          paths:
            - "~/.gradle"

      - run:
          name: Validate Code
          command: ./gradlew check

      - run:
          name: Copy Artifacts
          command: |
              mkdir -p ~/test-results
              find . -maxdepth 5 -name 'TEST-*.xml' -exec cp {} ~/test-results/ \;

      - store_test_results:
          path: ~/test-results/

      - setup_remote_docker

      - deploy:
          name: Deploy To Google Cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $GOOGLE_CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
              gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
              gcloud config set project $GCLOUD_PROJECT
              docker login -e 1234@5678.com -u _json_key -p "$(cat ${HOME}/client-secret.json)" https://us.gcr.io
              ./gradlew claimVersion -d --console=plain
              ./gradlew clean :docker:pushContainers --console=plain
            fi
