[versions]
kotlin = { version = "1.2.51", group = "org.jetbrains.kotlin" }
jackson = { version = "2.9.6", group = "com.fasterxml.jackson.core" }
jacksonData = { version = "2.9.6", group = "com.fasterxml.jackson.datatype" }
jacksonModule = { version = "2.9.6", group = "com.fasterxml.jackson.module" }
spring = { version = "5.1.2.RELEASE", group = "org.springframework" }
springBoot = { version = "2.1.0.RELEASE", group = "org.springframework.boot" }
springSecurity = { version = "5.1.1.RELEASE", group = "org.springframework.security" }

[libraries]
common = [
    'com.google.guava:guava:26.0-jre',
    'org.hibernate.validator:hibernate-validator:6.0.12.Final',
    'org.glassfish:javax.el:3.0.1-b08',
    "io.dropwizard.metrics:metrics-core:3.1.2",
    'commons-codec:commons-codec:1.11'
]

kotlin = [
    "org.jetbrains.kotlin:kotlin-stdlib",
    "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
    "org.jetbrains.kotlin:kotlin-reflect"
]

logging = [
    "org.slf4j:slf4j-api:1.7.25",
    'org.apache.logging.log4j:log4j-core:2.11.1',
    'org.apache.logging.log4j:log4j-slf4j18-impl:2.11.1'
]

ehcache = [
    'net.sf.ehcache:ehcache:2.10.4'
]

groovy = [
    'org.codehaus.groovy:groovy-all:2.5.4'
]

spring = [
    'org.springframework:spring-context',
    'org.springframework:spring-webmvc',
    'org.springframework:spring-tx',
    'org.springframework:spring-jdbc',
    'org.springframework:spring-webflux',
    'org.springframework:spring-context-support',
    'org.springframework.boot:spring-boot',
    'org.springframework.boot:spring-boot-autoconfigure',
    'org.springframework.boot:spring-boot-starter',
    'org.springframework.boot:spring-boot-starter-aop',
    'org.springframework.boot:spring-boot-actuator',
    'org.springframework.boot:spring-boot-starter-actuator'
]

springTest = [
    'org.springframework:spring-test',
    'org.springframework.security:spring-security-test'
]

httpClient = [
    'io.projectreactor.netty:reactor-netty:0.8.2.RELEASE',
    'io.mikael:urlbuilder:2.0.9'
]

database = [
    "mysql:mysql-connector-java:8.0.11",
    "com.zaxxer:HikariCP:3.2.0",
    "org.jooq:jooq:3.11.3",
    "org.jooq:jooq-meta:3.11.3",
    "org.flywaydb:flyway-core:5.2.1"
]

commonsLang = [
        "org.apache.commons:commons-lang3:3.7"
]

aspectJ = [
    'org.aspectj:aspectjweaver:1.8.8'
]

freemarker = [
    'org.freemarker:freemarker:2.3.28'
]

springAnnotation = [
    "org.springframework.boot:spring-boot-configuration-processor"
]

jackson = [
        "com.fasterxml.jackson.core:jackson-annotations",
        "com.fasterxml.jackson.core:jackson-databind",
        "com.fasterxml.jackson.datatype:jackson-datatype-jsr310",
        "com.fasterxml.jackson.module:jackson-module-kotlin"
]

jooqCodeGen = [
    "org.jooq:jooq:3.11.3",
    "org.jooq:jooq-meta:3.11.3",
    "org.jooq:jooq-codegen:3.11.3",
    "mysql:mysql-connector-java:8.0.11"
]

testingLibraries = [
    "org.mockito:mockito-core:1.10.19",
    "com.jayway.jsonpath:json-path:2.2.0",
    "cglib:cglib:3.2.5",
    "org.objenesis:objenesis:2.2",
    "org.ow2.asm:asm:5.0.4",
    "de.sven-jacobs:loremipsum:1.0",
    "org.jetbrains.kotlin:kotlin-test-junit5:1.2.51",
    'com.github.tomakehurst:wiremock:2.18.0',
    'org.hamcrest:hamcrest-library:1.3',
    'org.assertj:assertj-core:3.9.1',
    'org.spockframework:spock-core:1.2-groovy-2.5'
]

codec = [
    'commons-codec:commons-codec:1.11'
]

googleCloud = [
    "com.google.api-client:google-api-client:1.22.0",
    "com.google.apis:google-api-services-storage:v1-rev83-1.22.0"
]
