auth:
    domain: localhost
    client:
        google:
            client:
                id: 501986272416-882h8qm11sherv2m99geckohi2mrmffh.apps.googleusercontent.com
            client:
                secret: qHv-RKsHe5zavBhjWwXmktMr
        github:
            client:
                clientId: 429f464a7132f07de230
                clientSecret: dccb8a804a0da2a623c4a03b650b36b076a8aea1
                accessTokenUri: https://github.com/login/oauth/access_token
                userAuthorizationUri: https://github.com/login/oauth/authorize
                clientAuthenticationScheme: form
            resource:
                userInfoUri: https://api.github.com/user

server:
    port: 8080

management:
    context-path: /admin
    port: 8081

jwt:
    signing:
        key: secret

logging:
    level:
        io:
            ehdev: DEBUG
        org:
            pac4j: DEBUG
            jooq: DEBUG

flyway:
    out-of-order: true

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: verify

