/*
 * This file is generated by jOOQ.
*/
package tech.crom.db.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import tech.crom.db.tables.VersionBumpersTable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "version_bumpers", schema = "version_manager_test")
public class VersionBumpersRecord extends UpdatableRecordImpl<VersionBumpersRecord> implements Record4<Long, String, String, String> {

    private static final long serialVersionUID = -1046486595;

    /**
     * Setter for <code>version_manager_test.version_bumpers.version_bumper_id</code>.
     */
    public void setVersionBumperId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>version_manager_test.version_bumpers.version_bumper_id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "version_bumper_id", unique = true, nullable = false, precision = 19)
    @NotNull
    public Long getVersionBumperId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>version_manager_test.version_bumpers.bumper_name</code>.
     */
    public void setBumperName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>version_manager_test.version_bumpers.bumper_name</code>.
     */
    @Column(name = "bumper_name", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getBumperName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>version_manager_test.version_bumpers.class_name</code>.
     */
    public void setClassName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>version_manager_test.version_bumpers.class_name</code>.
     */
    @Column(name = "class_name", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getClassName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>version_manager_test.version_bumpers.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>version_manager_test.version_bumpers.description</code>.
     */
    @Column(name = "description", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return VersionBumpersTable.VERSION_BUMPERS.VERSION_BUMPER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return VersionBumpersTable.VERSION_BUMPERS.BUMPER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return VersionBumpersTable.VERSION_BUMPERS.CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return VersionBumpersTable.VERSION_BUMPERS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getVersionBumperId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBumperName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionBumpersRecord value1(Long value) {
        setVersionBumperId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionBumpersRecord value2(String value) {
        setBumperName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionBumpersRecord value3(String value) {
        setClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionBumpersRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionBumpersRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VersionBumpersRecord
     */
    public VersionBumpersRecord() {
        super(VersionBumpersTable.VERSION_BUMPERS);
    }

    /**
     * Create a detached, initialised VersionBumpersRecord
     */
    public VersionBumpersRecord(Long versionBumperId, String bumperName, String className, String description) {
        super(VersionBumpersTable.VERSION_BUMPERS);

        set(0, versionBumperId);
        set(1, bumperName);
        set(2, className);
        set(3, description);
    }
}
