/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db;


import io.ehdev.conrad.db.tables.CommitDetailsTable;
import io.ehdev.conrad.db.tables.CommitMetadataTable;
import io.ehdev.conrad.db.tables.ProjectDetailsTable;
import io.ehdev.conrad.db.tables.RepoDetailsTable;
import io.ehdev.conrad.db.tables.ResourceDetailLookupTable;
import io.ehdev.conrad.db.tables.TokenAuthenticationsTable;
import io.ehdev.conrad.db.tables.TokenJoinTable;
import io.ehdev.conrad.db.tables.UserDetailsTable;
import io.ehdev.conrad.db.tables.UserPermissionsTable;
import io.ehdev.conrad.db.tables.UserSecurityClientProfileTable;
import io.ehdev.conrad.db.tables.VersionBumpersTable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1989693882;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.commit_details</code>.
     */
    public final CommitDetailsTable COMMIT_DETAILS = io.ehdev.conrad.db.tables.CommitDetailsTable.COMMIT_DETAILS;

    /**
     * The table <code>public.commit_metadata</code>.
     */
    public final CommitMetadataTable COMMIT_METADATA = io.ehdev.conrad.db.tables.CommitMetadataTable.COMMIT_METADATA;

    /**
     * The table <code>public.project_details</code>.
     */
    public final ProjectDetailsTable PROJECT_DETAILS = io.ehdev.conrad.db.tables.ProjectDetailsTable.PROJECT_DETAILS;

    /**
     * The table <code>public.repo_details</code>.
     */
    public final RepoDetailsTable REPO_DETAILS = io.ehdev.conrad.db.tables.RepoDetailsTable.REPO_DETAILS;

    /**
     * The table <code>public.resource_detail_lookup</code>.
     */
    public final ResourceDetailLookupTable RESOURCE_DETAIL_LOOKUP = io.ehdev.conrad.db.tables.ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP;

    /**
     * The table <code>public.token_authentications</code>.
     */
    public final TokenAuthenticationsTable TOKEN_AUTHENTICATIONS = io.ehdev.conrad.db.tables.TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS;

    /**
     * The table <code>public.token_join</code>.
     */
    public final TokenJoinTable TOKEN_JOIN = io.ehdev.conrad.db.tables.TokenJoinTable.TOKEN_JOIN;

    /**
     * The table <code>public.user_details</code>.
     */
    public final UserDetailsTable USER_DETAILS = io.ehdev.conrad.db.tables.UserDetailsTable.USER_DETAILS;

    /**
     * The table <code>public.user_permissions</code>.
     */
    public final UserPermissionsTable USER_PERMISSIONS = io.ehdev.conrad.db.tables.UserPermissionsTable.USER_PERMISSIONS;

    /**
     * The table <code>public.user_security_client_profile</code>.
     */
    public final UserSecurityClientProfileTable USER_SECURITY_CLIENT_PROFILE = io.ehdev.conrad.db.tables.UserSecurityClientProfileTable.USER_SECURITY_CLIENT_PROFILE;

    /**
     * The table <code>public.version_bumpers</code>.
     */
    public final VersionBumpersTable VERSION_BUMPERS = io.ehdev.conrad.db.tables.VersionBumpersTable.VERSION_BUMPERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CommitDetailsTable.COMMIT_DETAILS,
            CommitMetadataTable.COMMIT_METADATA,
            ProjectDetailsTable.PROJECT_DETAILS,
            RepoDetailsTable.REPO_DETAILS,
            ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP,
            TokenAuthenticationsTable.TOKEN_AUTHENTICATIONS,
            TokenJoinTable.TOKEN_JOIN,
            UserDetailsTable.USER_DETAILS,
            UserPermissionsTable.USER_PERMISSIONS,
            UserSecurityClientProfileTable.USER_SECURITY_CLIENT_PROFILE,
            VersionBumpersTable.VERSION_BUMPERS);
    }
}
