/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db;


import io.ehdev.conrad.db.tables.CommitDetailsTable;
import io.ehdev.conrad.db.tables.CommitMetadataTable;
import io.ehdev.conrad.db.tables.ProjectDetailsTable;
import io.ehdev.conrad.db.tables.RepoDetailsTable;
import io.ehdev.conrad.db.tables.UserDetailsTable;
import io.ehdev.conrad.db.tables.UserPermissionsTable;
import io.ehdev.conrad.db.tables.UserSecurityClientProfileTable;
import io.ehdev.conrad.db.tables.UserTokensTable;
import io.ehdev.conrad.db.tables.VersionBumpersTable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.commit_details
	 */
	public static final CommitDetailsTable COMMIT_DETAILS = io.ehdev.conrad.db.tables.CommitDetailsTable.COMMIT_DETAILS;

	/**
	 * The table public.commit_metadata
	 */
	public static final CommitMetadataTable COMMIT_METADATA = io.ehdev.conrad.db.tables.CommitMetadataTable.COMMIT_METADATA;

	/**
	 * The table public.project_details
	 */
	public static final ProjectDetailsTable PROJECT_DETAILS = io.ehdev.conrad.db.tables.ProjectDetailsTable.PROJECT_DETAILS;

	/**
	 * The table public.repo_details
	 */
	public static final RepoDetailsTable REPO_DETAILS = io.ehdev.conrad.db.tables.RepoDetailsTable.REPO_DETAILS;

	/**
	 * The table public.user_details
	 */
	public static final UserDetailsTable USER_DETAILS = io.ehdev.conrad.db.tables.UserDetailsTable.USER_DETAILS;

	/**
	 * The table public.user_permissions
	 */
	public static final UserPermissionsTable USER_PERMISSIONS = io.ehdev.conrad.db.tables.UserPermissionsTable.USER_PERMISSIONS;

	/**
	 * The table public.user_security_client_profile
	 */
	public static final UserSecurityClientProfileTable USER_SECURITY_CLIENT_PROFILE = io.ehdev.conrad.db.tables.UserSecurityClientProfileTable.USER_SECURITY_CLIENT_PROFILE;

	/**
	 * The table public.user_tokens
	 */
	public static final UserTokensTable USER_TOKENS = io.ehdev.conrad.db.tables.UserTokensTable.USER_TOKENS;

	/**
	 * The table public.version_bumpers
	 */
	public static final VersionBumpersTable VERSION_BUMPERS = io.ehdev.conrad.db.tables.VersionBumpersTable.VERSION_BUMPERS;
}
