/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db;


import io.ehdev.conrad.db.tables.AclClassTable;
import io.ehdev.conrad.db.tables.AclEntryTable;
import io.ehdev.conrad.db.tables.AclObjectIdentityTable;
import io.ehdev.conrad.db.tables.AclSidTable;
import io.ehdev.conrad.db.tables.CommitDetailsTable;
import io.ehdev.conrad.db.tables.CommitMetadataTable;
import io.ehdev.conrad.db.tables.ProjectDetailsTable;
import io.ehdev.conrad.db.tables.RepoDetailsTable;
import io.ehdev.conrad.db.tables.RepositoryTokensTable;
import io.ehdev.conrad.db.tables.SsUserconnectionTable;
import io.ehdev.conrad.db.tables.UserDetailsTable;
import io.ehdev.conrad.db.tables.UserTokensTable;
import io.ehdev.conrad.db.tables.VersionBumpersTable;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.acl_class</code>.
     */
    public static final AclClassTable ACL_CLASS = io.ehdev.conrad.db.tables.AclClassTable.ACL_CLASS;

    /**
     * The table <code>public.acl_entry</code>.
     */
    public static final AclEntryTable ACL_ENTRY = io.ehdev.conrad.db.tables.AclEntryTable.ACL_ENTRY;

    /**
     * The table <code>public.acl_object_identity</code>.
     */
    public static final AclObjectIdentityTable ACL_OBJECT_IDENTITY = io.ehdev.conrad.db.tables.AclObjectIdentityTable.ACL_OBJECT_IDENTITY;

    /**
     * The table <code>public.acl_sid</code>.
     */
    public static final AclSidTable ACL_SID = io.ehdev.conrad.db.tables.AclSidTable.ACL_SID;

    /**
     * The table <code>public.commit_details</code>.
     */
    public static final CommitDetailsTable COMMIT_DETAILS = io.ehdev.conrad.db.tables.CommitDetailsTable.COMMIT_DETAILS;

    /**
     * The table <code>public.commit_metadata</code>.
     */
    public static final CommitMetadataTable COMMIT_METADATA = io.ehdev.conrad.db.tables.CommitMetadataTable.COMMIT_METADATA;

    /**
     * The table <code>public.project_details</code>.
     */
    public static final ProjectDetailsTable PROJECT_DETAILS = io.ehdev.conrad.db.tables.ProjectDetailsTable.PROJECT_DETAILS;

    /**
     * The table <code>public.repo_details</code>.
     */
    public static final RepoDetailsTable REPO_DETAILS = io.ehdev.conrad.db.tables.RepoDetailsTable.REPO_DETAILS;

    /**
     * The table <code>public.repository_tokens</code>.
     */
    public static final RepositoryTokensTable REPOSITORY_TOKENS = io.ehdev.conrad.db.tables.RepositoryTokensTable.REPOSITORY_TOKENS;

    /**
     * The table <code>public.ss_userconnection</code>.
     */
    public static final SsUserconnectionTable SS_USERCONNECTION = io.ehdev.conrad.db.tables.SsUserconnectionTable.SS_USERCONNECTION;

    /**
     * The table <code>public.user_details</code>.
     */
    public static final UserDetailsTable USER_DETAILS = io.ehdev.conrad.db.tables.UserDetailsTable.USER_DETAILS;

    /**
     * The table <code>public.user_tokens</code>.
     */
    public static final UserTokensTable USER_TOKENS = io.ehdev.conrad.db.tables.UserTokensTable.USER_TOKENS;

    /**
     * The table <code>public.version_bumpers</code>.
     */
    public static final VersionBumpersTable VERSION_BUMPERS = io.ehdev.conrad.db.tables.VersionBumpersTable.VERSION_BUMPERS;
}
