/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "commit_details", schema = "public", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"commit_id", "vcs_repo_uuid"}),
	@UniqueConstraint(columnNames = {"version", "vcs_repo_uuid"})
})
public class CommitDetails implements Serializable {

	private static final long serialVersionUID = 1856764854;

	private UUID      uuid;
	private UUID      vcsRepoUuid;
	private UUID      parentCommitUuid;
	private String    commitId;
	private String    version;
	private Timestamp createdAt;

	public CommitDetails() {}

	public CommitDetails(CommitDetails value) {
		this.uuid = value.uuid;
		this.vcsRepoUuid = value.vcsRepoUuid;
		this.parentCommitUuid = value.parentCommitUuid;
		this.commitId = value.commitId;
		this.version = value.version;
		this.createdAt = value.createdAt;
	}

	public CommitDetails(
		UUID      uuid,
		UUID      vcsRepoUuid,
		UUID      parentCommitUuid,
		String    commitId,
		String    version,
		Timestamp createdAt
	) {
		this.uuid = uuid;
		this.vcsRepoUuid = vcsRepoUuid;
		this.parentCommitUuid = parentCommitUuid;
		this.commitId = commitId;
		this.version = version;
		this.createdAt = createdAt;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false)
	@NotNull
	public UUID getUuid() {
		return this.uuid;
	}

	public void setUuid(UUID uuid) {
		this.uuid = uuid;
	}

	@Column(name = "vcs_repo_uuid", nullable = false)
	@NotNull
	public UUID getVcsRepoUuid() {
		return this.vcsRepoUuid;
	}

	public void setVcsRepoUuid(UUID vcsRepoUuid) {
		this.vcsRepoUuid = vcsRepoUuid;
	}

	@Column(name = "parent_commit_uuid")
	public UUID getParentCommitUuid() {
		return this.parentCommitUuid;
	}

	public void setParentCommitUuid(UUID parentCommitUuid) {
		this.parentCommitUuid = parentCommitUuid;
	}

	@Column(name = "commit_id", nullable = false, length = 40)
	@NotNull
	@Size(max = 40)
	public String getCommitId() {
		return this.commitId;
	}

	public void setCommitId(String commitId) {
		this.commitId = commitId;
	}

	@Column(name = "version", nullable = false, length = 120)
	@NotNull
	@Size(max = 120)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "created_at", nullable = false)
	@NotNull
	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CommitDetails (");

		sb.append(uuid);
		sb.append(", ").append(vcsRepoUuid);
		sb.append(", ").append(parentCommitUuid);
		sb.append(", ").append(commitId);
		sb.append(", ").append(version);
		sb.append(", ").append(createdAt);

		sb.append(")");
		return sb.toString();
	}
}
