/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "acl_object_identity", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"object_id_class", "object_id_identity"})
})
public class AclObjectIdentity implements Serializable {

    private static final long serialVersionUID = 1935662851;

    private Long    id;
    private Long    objectIdClass;
    private Long    objectIdIdentity;
    private Long    parentObject;
    private Long    ownerSid;
    private Boolean entriesInheriting;

    public AclObjectIdentity() {}

    public AclObjectIdentity(AclObjectIdentity value) {
        this.id = value.id;
        this.objectIdClass = value.objectIdClass;
        this.objectIdIdentity = value.objectIdIdentity;
        this.parentObject = value.parentObject;
        this.ownerSid = value.ownerSid;
        this.entriesInheriting = value.entriesInheriting;
    }

    public AclObjectIdentity(
        Long    id,
        Long    objectIdClass,
        Long    objectIdIdentity,
        Long    parentObject,
        Long    ownerSid,
        Boolean entriesInheriting
    ) {
        this.id = id;
        this.objectIdClass = objectIdClass;
        this.objectIdIdentity = objectIdIdentity;
        this.parentObject = parentObject;
        this.ownerSid = ownerSid;
        this.entriesInheriting = entriesInheriting;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 64)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "object_id_class", nullable = false, precision = 64)
    @NotNull
    public Long getObjectIdClass() {
        return this.objectIdClass;
    }

    public void setObjectIdClass(Long objectIdClass) {
        this.objectIdClass = objectIdClass;
    }

    @Column(name = "object_id_identity", nullable = false, precision = 64)
    @NotNull
    public Long getObjectIdIdentity() {
        return this.objectIdIdentity;
    }

    public void setObjectIdIdentity(Long objectIdIdentity) {
        this.objectIdIdentity = objectIdIdentity;
    }

    @Column(name = "parent_object", precision = 64)
    public Long getParentObject() {
        return this.parentObject;
    }

    public void setParentObject(Long parentObject) {
        this.parentObject = parentObject;
    }

    @Column(name = "owner_sid", precision = 64)
    public Long getOwnerSid() {
        return this.ownerSid;
    }

    public void setOwnerSid(Long ownerSid) {
        this.ownerSid = ownerSid;
    }

    @Column(name = "entries_inheriting", nullable = false)
    @NotNull
    public Boolean getEntriesInheriting() {
        return this.entriesInheriting;
    }

    public void setEntriesInheriting(Boolean entriesInheriting) {
        this.entriesInheriting = entriesInheriting;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AclObjectIdentity (");

        sb.append(id);
        sb.append(", ").append(objectIdClass);
        sb.append(", ").append(objectIdIdentity);
        sb.append(", ").append(parentObject);
        sb.append(", ").append(ownerSid);
        sb.append(", ").append(entriesInheriting);

        sb.append(")");
        return sb.toString();
    }
}
