/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user_security_client_profile", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"provider_type", "provider_user_id"})
})
public class UserSecurityClientProfile implements Serializable {

    private static final long serialVersionUID = -1018675335;

    private UUID   uuid;
    private UUID   userUuid;
    private String providerType;
    private String providerUserId;

    public UserSecurityClientProfile() {}

    public UserSecurityClientProfile(UserSecurityClientProfile value) {
        this.uuid = value.uuid;
        this.userUuid = value.userUuid;
        this.providerType = value.providerType;
        this.providerUserId = value.providerUserId;
    }

    public UserSecurityClientProfile(
        UUID   uuid,
        UUID   userUuid,
        String providerType,
        String providerUserId
    ) {
        this.uuid = uuid;
        this.userUuid = userUuid;
        this.providerType = providerType;
        this.providerUserId = providerUserId;
    }

    @Id
    @Column(name = "uuid", unique = true, nullable = false)
    public UUID getUuid() {
        return this.uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    @Column(name = "user_uuid", nullable = false)
    @NotNull
    public UUID getUserUuid() {
        return this.userUuid;
    }

    public void setUserUuid(UUID userUuid) {
        this.userUuid = userUuid;
    }

    @Column(name = "provider_type", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getProviderType() {
        return this.providerType;
    }

    public void setProviderType(String providerType) {
        this.providerType = providerType;
    }

    @Column(name = "provider_user_id", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    public String getProviderUserId() {
        return this.providerUserId;
    }

    public void setProviderUserId(String providerUserId) {
        this.providerUserId = providerUserId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSecurityClientProfile (");

        sb.append(uuid);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(providerType);
        sb.append(", ").append(providerUserId);

        sb.append(")");
        return sb.toString();
    }
}
