/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.daos;


import io.ehdev.conrad.db.tables.AclClassTable;
import io.ehdev.conrad.db.tables.pojos.AclClass;
import io.ehdev.conrad.db.tables.records.AclClassRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclClassDao extends DAOImpl<AclClassRecord, AclClass, Long> {

    /**
     * Create a new AclClassDao without any configuration
     */
    public AclClassDao() {
        super(AclClassTable.ACL_CLASS, AclClass.class);
    }

    /**
     * Create a new AclClassDao with an attached configuration
     */
    public AclClassDao(Configuration configuration) {
        super(AclClassTable.ACL_CLASS, AclClass.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(AclClass object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<AclClass> fetchById(Long... values) {
        return fetch(AclClassTable.ACL_CLASS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public AclClass fetchOneById(Long value) {
        return fetchOne(AclClassTable.ACL_CLASS.ID, value);
    }

    /**
     * Fetch records that have <code>class IN (values)</code>
     */
    public List<AclClass> fetchByClass(String... values) {
        return fetch(AclClassTable.ACL_CLASS.CLASS, values);
    }

    /**
     * Fetch a unique record that has <code>class = value</code>
     */
    public AclClass fetchOneByClass(String value) {
        return fetchOne(AclClassTable.ACL_CLASS.CLASS, value);
    }
}
