/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.daos;


import io.ehdev.conrad.db.tables.CommitMetadataTable;
import io.ehdev.conrad.db.tables.pojos.CommitMetadata;
import io.ehdev.conrad.db.tables.records.CommitMetadataRecord;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommitMetadataDao extends DAOImpl<CommitMetadataRecord, CommitMetadata, UUID> {

	/**
	 * Create a new CommitMetadataDao without any configuration
	 */
	public CommitMetadataDao() {
		super(CommitMetadataTable.COMMIT_METADATA, CommitMetadata.class);
	}

	/**
	 * Create a new CommitMetadataDao with an attached configuration
	 */
	public CommitMetadataDao(Configuration configuration) {
		super(CommitMetadataTable.COMMIT_METADATA, CommitMetadata.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected UUID getId(CommitMetadata object) {
		return object.getUuid();
	}

	/**
	 * Fetch records that have <code>uuid IN (values)</code>
	 */
	public List<CommitMetadata> fetchByUuid(UUID... values) {
		return fetch(CommitMetadataTable.COMMIT_METADATA.UUID, values);
	}

	/**
	 * Fetch a unique record that has <code>uuid = value</code>
	 */
	public CommitMetadata fetchOneByUuid(UUID value) {
		return fetchOne(CommitMetadataTable.COMMIT_METADATA.UUID, value);
	}

	/**
	 * Fetch records that have <code>commit_uuid IN (values)</code>
	 */
	public List<CommitMetadata> fetchByCommitUuid(UUID... values) {
		return fetch(CommitMetadataTable.COMMIT_METADATA.COMMIT_UUID, values);
	}

	/**
	 * Fetch records that have <code>repo_details_uuid IN (values)</code>
	 */
	public List<CommitMetadata> fetchByRepoDetailsUuid(UUID... values) {
		return fetch(CommitMetadataTable.COMMIT_METADATA.REPO_DETAILS_UUID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<CommitMetadata> fetchByName(String... values) {
		return fetch(CommitMetadataTable.COMMIT_METADATA.NAME, values);
	}

	/**
	 * Fetch records that have <code>text IN (values)</code>
	 */
	public List<CommitMetadata> fetchByText(String... values) {
		return fetch(CommitMetadataTable.COMMIT_METADATA.TEXT, values);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public List<CommitMetadata> fetchByCreatedAt(Instant... values) {
		return fetch(CommitMetadataTable.COMMIT_METADATA.CREATED_AT, values);
	}

	/**
	 * Fetch records that have <code>updated_at IN (values)</code>
	 */
	public List<CommitMetadata> fetchByUpdatedAt(Instant... values) {
		return fetch(CommitMetadataTable.COMMIT_METADATA.UPDATED_AT, values);
	}
}
