/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.daos;


import io.ehdev.conrad.db.tables.ResourceDetailLookupTable;
import io.ehdev.conrad.db.tables.pojos.ResourceDetailLookup;
import io.ehdev.conrad.db.tables.records.ResourceDetailLookupRecord;

import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceDetailLookupDao extends DAOImpl<ResourceDetailLookupRecord, ResourceDetailLookup, UUID> {

    /**
     * Create a new ResourceDetailLookupDao without any configuration
     */
    public ResourceDetailLookupDao() {
        super(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP, ResourceDetailLookup.class);
    }

    /**
     * Create a new ResourceDetailLookupDao with an attached configuration
     */
    public ResourceDetailLookupDao(Configuration configuration) {
        super(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP, ResourceDetailLookup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(ResourceDetailLookup object) {
        return object.getUuid();
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<ResourceDetailLookup> fetchByUuid(UUID... values) {
        return fetch(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public ResourceDetailLookup fetchOneByUuid(UUID value) {
        return fetchOne(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP.UUID, value);
    }

    /**
     * Fetch records that have <code>project_name IN (values)</code>
     */
    public List<ResourceDetailLookup> fetchByProjectName(String... values) {
        return fetch(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP.PROJECT_NAME, values);
    }

    /**
     * Fetch records that have <code>repo_name IN (values)</code>
     */
    public List<ResourceDetailLookup> fetchByRepoName(String... values) {
        return fetch(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP.REPO_NAME, values);
    }

    /**
     * Fetch records that have <code>project_uuid IN (values)</code>
     */
    public List<ResourceDetailLookup> fetchByProjectUuid(UUID... values) {
        return fetch(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP.PROJECT_UUID, values);
    }

    /**
     * Fetch records that have <code>repo_uuid IN (values)</code>
     */
    public List<ResourceDetailLookup> fetchByRepoUuid(UUID... values) {
        return fetch(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP.REPO_UUID, values);
    }

    /**
     * Fetch a unique record that has <code>repo_uuid = value</code>
     */
    public ResourceDetailLookup fetchOneByRepoUuid(UUID value) {
        return fetchOne(ResourceDetailLookupTable.RESOURCE_DETAIL_LOOKUP.REPO_UUID, value);
    }
}
