/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.daos;


import io.ehdev.conrad.db.tables.VersionBumpersTable;
import io.ehdev.conrad.db.tables.pojos.VersionBumpers;
import io.ehdev.conrad.db.tables.records.VersionBumpersRecord;

import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VersionBumpersDao extends DAOImpl<VersionBumpersRecord, VersionBumpers, UUID> {

    /**
     * Create a new VersionBumpersDao without any configuration
     */
    public VersionBumpersDao() {
        super(VersionBumpersTable.VERSION_BUMPERS, VersionBumpers.class);
    }

    /**
     * Create a new VersionBumpersDao with an attached configuration
     */
    public VersionBumpersDao(Configuration configuration) {
        super(VersionBumpersTable.VERSION_BUMPERS, VersionBumpers.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UUID getId(VersionBumpers object) {
        return object.getUuid();
    }

    /**
     * Fetch records that have <code>uuid IN (values)</code>
     */
    public List<VersionBumpers> fetchByUuid(UUID... values) {
        return fetch(VersionBumpersTable.VERSION_BUMPERS.UUID, values);
    }

    /**
     * Fetch a unique record that has <code>uuid = value</code>
     */
    public VersionBumpers fetchOneByUuid(UUID value) {
        return fetchOne(VersionBumpersTable.VERSION_BUMPERS.UUID, value);
    }

    /**
     * Fetch records that have <code>bumper_name IN (values)</code>
     */
    public List<VersionBumpers> fetchByBumperName(String... values) {
        return fetch(VersionBumpersTable.VERSION_BUMPERS.BUMPER_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>bumper_name = value</code>
     */
    public VersionBumpers fetchOneByBumperName(String value) {
        return fetchOne(VersionBumpersTable.VERSION_BUMPERS.BUMPER_NAME, value);
    }

    /**
     * Fetch records that have <code>class_name IN (values)</code>
     */
    public List<VersionBumpers> fetchByClassName(String... values) {
        return fetch(VersionBumpersTable.VERSION_BUMPERS.CLASS_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>class_name = value</code>
     */
    public VersionBumpers fetchOneByClassName(String value) {
        return fetchOne(VersionBumpersTable.VERSION_BUMPERS.CLASS_NAME, value);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<VersionBumpers> fetchByDescription(String... values) {
        return fetch(VersionBumpersTable.VERSION_BUMPERS.DESCRIPTION, values);
    }
}
