auth:
    domain: 'localhost'
    client:
        google:
            client:
                id: 501986272416-882h8qm11sherv2m99geckohi2mrmffh.apps.googleusercontent.com
                secret: qHv-RKsHe5zavBhjWwXmktMr

server:
    port: 8080

management:
    context-path: /admin
    port: 8081

jwt:
    signing:
        key: secret

flyway:
    out-of-order: true

storage:
    engine: disk
    disk:
        root: build

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/version_manager_test?verifyServerCertificate=false&useSSL=true
        username: root
        password: password
        dbname: version_manager_test
    jpa:
        show-sql: true
