/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.daos;


import io.ehdev.conrad.db.tables.CommitDetails;
import io.ehdev.conrad.db.tables.records.CommitDetailsRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommitDetailsDao extends DAOImpl<CommitDetailsRecord, io.ehdev.conrad.db.tables.pojos.CommitDetails, UUID> {

	/**
	 * Create a new CommitDetailsDao without any configuration
	 */
	public CommitDetailsDao() {
		super(CommitDetails.COMMIT_DETAILS, io.ehdev.conrad.db.tables.pojos.CommitDetails.class);
	}

	/**
	 * Create a new CommitDetailsDao with an attached configuration
	 */
	public CommitDetailsDao(Configuration configuration) {
		super(CommitDetails.COMMIT_DETAILS, io.ehdev.conrad.db.tables.pojos.CommitDetails.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected UUID getId(io.ehdev.conrad.db.tables.pojos.CommitDetails object) {
		return object.getUuid();
	}

	/**
	 * Fetch records that have <code>uuid IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.CommitDetails> fetchByUuid(UUID... values) {
		return fetch(CommitDetails.COMMIT_DETAILS.UUID, values);
	}

	/**
	 * Fetch a unique record that has <code>uuid = value</code>
	 */
	public io.ehdev.conrad.db.tables.pojos.CommitDetails fetchOneByUuid(UUID value) {
		return fetchOne(CommitDetails.COMMIT_DETAILS.UUID, value);
	}

	/**
	 * Fetch records that have <code>vcs_repo_uuid IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.CommitDetails> fetchByVcsRepoUuid(UUID... values) {
		return fetch(CommitDetails.COMMIT_DETAILS.VCS_REPO_UUID, values);
	}

	/**
	 * Fetch records that have <code>parent_commit_uuid IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.CommitDetails> fetchByParentCommitUuid(UUID... values) {
		return fetch(CommitDetails.COMMIT_DETAILS.PARENT_COMMIT_UUID, values);
	}

	/**
	 * Fetch records that have <code>commit_id IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.CommitDetails> fetchByCommitId(String... values) {
		return fetch(CommitDetails.COMMIT_DETAILS.COMMIT_ID, values);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.CommitDetails> fetchByVersion(String... values) {
		return fetch(CommitDetails.COMMIT_DETAILS.VERSION, values);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.CommitDetails> fetchByCreatedAt(Timestamp... values) {
		return fetch(CommitDetails.COMMIT_DETAILS.CREATED_AT, values);
	}
}
