/**
 * This class is generated by jOOQ
 */
package io.ehdev.conrad.db.tables.daos;


import io.ehdev.conrad.db.tables.UserToken;
import io.ehdev.conrad.db.tables.records.UserTokenRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTokenDao extends DAOImpl<UserTokenRecord, io.ehdev.conrad.db.tables.pojos.UserToken, UUID> {

	/**
	 * Create a new UserTokenDao without any configuration
	 */
	public UserTokenDao() {
		super(UserToken.USER_TOKEN, io.ehdev.conrad.db.tables.pojos.UserToken.class);
	}

	/**
	 * Create a new UserTokenDao with an attached configuration
	 */
	public UserTokenDao(Configuration configuration) {
		super(UserToken.USER_TOKEN, io.ehdev.conrad.db.tables.pojos.UserToken.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected UUID getId(io.ehdev.conrad.db.tables.pojos.UserToken object) {
		return object.getUuid();
	}

	/**
	 * Fetch records that have <code>uuid IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.UserToken> fetchByUuid(UUID... values) {
		return fetch(UserToken.USER_TOKEN.UUID, values);
	}

	/**
	 * Fetch a unique record that has <code>uuid = value</code>
	 */
	public io.ehdev.conrad.db.tables.pojos.UserToken fetchOneByUuid(UUID value) {
		return fetchOne(UserToken.USER_TOKEN.UUID, value);
	}

	/**
	 * Fetch records that have <code>user_uuid IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.UserToken> fetchByUserUuid(UUID... values) {
		return fetch(UserToken.USER_TOKEN.USER_UUID, values);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.UserToken> fetchByCreatedAt(Timestamp... values) {
		return fetch(UserToken.USER_TOKEN.CREATED_AT, values);
	}

	/**
	 * Fetch records that have <code>expires_at IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.UserToken> fetchByExpiresAt(Timestamp... values) {
		return fetch(UserToken.USER_TOKEN.EXPIRES_AT, values);
	}

	/**
	 * Fetch records that have <code>valid IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.UserToken> fetchByValid(Boolean... values) {
		return fetch(UserToken.USER_TOKEN.VALID, values);
	}

	/**
	 * Fetch records that have <code>token_type IN (values)</code>
	 */
	public List<io.ehdev.conrad.db.tables.pojos.UserToken> fetchByTokenType(String... values) {
		return fetch(UserToken.USER_TOKEN.TOKEN_TYPE, values);
	}
}
