# Connect to the DB
spring:
    profiles: test
    datasource:
        url: jdbc:postgresql://172.0.1.100/version_manager_test
        username: version_manager_test
        password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
flyway:
    enabled: false

---

spring:
    profiles: dev
    datasource:
        url: jdbc:postgresql://172.0.1.100/version_manager
        username: version
        password: manager

---

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

server:
    port: 8080

management:
    context-path: /admin
    port: 8081
