google:
    clientId: 428210344673-bmar2c3qa5daop98pu9731l8v0tihrt1.apps.googleusercontent.com
    clientSecret: Y4UZtHiDP1R2o5_INu9MWykI

server:
    port: 8080

management:
    context-path: /admin
    port: 8081

jwt:
    signing:
        key: secret

security:
    text:
        password: password
        salt: 0123456789ABCDEF

logging:
    level:
        io:
            ehdev: DEBUG
        org:
            pac4j: DEBUG

flyway:
    out-of-order: true
    locations: classpath:db/security/migration, classpath:db/version/migration

spring:
    datasource:
        url: jdbc:postgresql://172.0.1.100/version_manager_test
        username: version_manager_test
        password: password
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: verify
