# Connect to the DB
spring:
    datasource:
        url: jdbc:postgresql://172.0.1.100/version_manager
        username: version
        password: manager

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate

server:
    port: 8080

management:
    context-path: /admin
#    security:
#        role: ADMIN
    port: 8081

#security:
#    oauth2:
#        client:
#            clientId: e26002913dce86419723
#            clientSecret: c8d18cb9b65212ad8acb3d0603a85f6bc3aa704f
#            accessTokenUri: https://github.com/login/oauth/access_token
#            userAuthorizationUri: https://github.com/login/oauth/authorize
#            clientAuthenticationScheme: form
#    resource:
#            userInfoUri: https://api.github.com/user
#            preferTokenInfo: false
#security:
#    oauth2:
#        client:
#            clientId: bd1c0a783ccdd1c9b9e4
#            clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#            accessTokenUri: https://github.com/login/oauth/access_token
#            userAuthorizationUri: https://github.com/login/oauth/authorize
#            clientAuthenticationScheme: form
