# Connect to the DB
spring:
    profiles: test
    datasource:
        url: jdbc:postgresql://172.0.1.100/version_manager_test
        username: version_manager_test
        password: password
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
flyway:
    enabled: false

---

spring:
    profiles: dev
    datasource:
        url: jdbc:postgresql://172.0.1.100/version_manager
        username: version
        password: manager

---

spring:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate
    oauth2:
        client:
          clientId: bd1c0a783ccdd1c9b9e4
          clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
          accessTokenUri: https://github.com/login/oauth/access_token
          userAuthorizationUri: https://github.com/login/oauth/authorize
          clientAuthenticationScheme: form
        resource:
          userInfoUri: https://api.github.com/user
          preferTokenInfo: false


server:
    port: 8080

management:
    context-path: /admin
    port: 8081
