auth:
    domain: 'localhost'
    client:
        google:
            client.id: 501986272416-882h8qm11sherv2m99geckohi2mrmffh.apps.googleusercontent.com
            client.secret: qHv-RKsHe5zavBhjWwXmktMr

web-ui:
    cors-domain: http://localhost:3000
    root-domain: http://localhost:3000
    login-page: /login
    root-page: /
    register-page: http://localhost:3000/

server:
    port: 8080

management:
    context-path: /admin
    port: 8081

jwt:
    signing:
        key: secret

flyway:
    out-of-order: true

storage:
    engine: disk
    disk:
        root: storage-tmp

spring:
    jmx.enabled: false
    datasource:
        url: jdbc:mysql://127.0.0.1:13306/version_manager_test?verifyServerCertificate=false&useSSL=true
        username: root
        password: password
    jpa:
        show-sql: true
