/*
 * This file is generated by jOOQ.
*/
package tech.crom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "acl_class", schema = "version_manager_test")
public class AclClass implements Serializable {

    private static final long serialVersionUID = 117724043;

    private ULong  id;
    private String class_;

    public AclClass() {}

    public AclClass(AclClass value) {
        this.id = value.id;
        this.class_ = value.class_;
    }

    public AclClass(
        ULong  id,
        String class_
    ) {
        this.id = id;
        this.class_ = class_;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, precision = 20)
    @NotNull
    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    @Column(name = "class", unique = true, nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AclClass (");

        sb.append(id);
        sb.append(", ").append(class_);

        sb.append(")");
        return sb.toString();
    }
}
