/**
 * This class is generated by jOOQ
 */
package tech.crom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "repo_details", schema = "version_manager_test")
public class RepoDetails implements Serializable {

    private static final long serialVersionUID = 245246897;

    private Long    repoDetailId;
    private String  repoName;
    private Long    projectId;
    private Long    versionBumperId;
    private String  url;
    private String  description;
    private Boolean public_;
    private Long    securityId;

    public RepoDetails() {}

    public RepoDetails(RepoDetails value) {
        this.repoDetailId = value.repoDetailId;
        this.repoName = value.repoName;
        this.projectId = value.projectId;
        this.versionBumperId = value.versionBumperId;
        this.url = value.url;
        this.description = value.description;
        this.public_ = value.public_;
        this.securityId = value.securityId;
    }

    public RepoDetails(
        Long    repoDetailId,
        String  repoName,
        Long    projectId,
        Long    versionBumperId,
        String  url,
        String  description,
        Boolean public_,
        Long    securityId
    ) {
        this.repoDetailId = repoDetailId;
        this.repoName = repoName;
        this.projectId = projectId;
        this.versionBumperId = versionBumperId;
        this.url = url;
        this.description = description;
        this.public_ = public_;
        this.securityId = securityId;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "repo_detail_id", unique = true, nullable = false, precision = 19)
    @NotNull
    public Long getRepoDetailId() {
        return this.repoDetailId;
    }

    public void setRepoDetailId(Long repoDetailId) {
        this.repoDetailId = repoDetailId;
    }

    @Column(name = "repo_name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getRepoName() {
        return this.repoName;
    }

    public void setRepoName(String repoName) {
        this.repoName = repoName;
    }

    @Column(name = "project_id", nullable = false, precision = 19)
    @NotNull
    public Long getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    @Column(name = "version_bumper_id", nullable = false, precision = 19)
    @NotNull
    public Long getVersionBumperId() {
        return this.versionBumperId;
    }

    public void setVersionBumperId(Long versionBumperId) {
        this.versionBumperId = versionBumperId;
    }

    @Column(name = "url", length = 65535)
    @Size(max = 65535)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "description", length = 65535)
    @Size(max = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "public")
    public Boolean getPublic() {
        return this.public_;
    }

    public void setPublic(Boolean public_) {
        this.public_ = public_;
    }

    @Column(name = "security_id", nullable = false, precision = 19)
    @NotNull
    public Long getSecurityId() {
        return this.securityId;
    }

    public void setSecurityId(Long securityId) {
        this.securityId = securityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RepoDetails (");

        sb.append(repoDetailId);
        sb.append(", ").append(repoName);
        sb.append(", ").append(projectId);
        sb.append(", ").append(versionBumperId);
        sb.append(", ").append(url);
        sb.append(", ").append(description);
        sb.append(", ").append(public_);
        sb.append(", ").append(securityId);

        sb.append(")");
        return sb.toString();
    }
}
