/**
 * This class is generated by jOOQ
 */
package tech.crom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "repo_details", schema = "version_manager_test")
public class RepoDetails implements Serializable {

    private static final long serialVersionUID = -1806142315;

    private Long   repoDetailsId;
    private String repoName;
    private Long   projectId;
    private Long   versionBumperId;
    private String url;
    private String description;
    private Byte   public_;
    private Long   securityId;

    public RepoDetails() {}

    public RepoDetails(RepoDetails value) {
        this.repoDetailsId = value.repoDetailsId;
        this.repoName = value.repoName;
        this.projectId = value.projectId;
        this.versionBumperId = value.versionBumperId;
        this.url = value.url;
        this.description = value.description;
        this.public_ = value.public_;
        this.securityId = value.securityId;
    }

    public RepoDetails(
        Long   repoDetailsId,
        String repoName,
        Long   projectId,
        Long   versionBumperId,
        String url,
        String description,
        Byte   public_,
        Long   securityId
    ) {
        this.repoDetailsId = repoDetailsId;
        this.repoName = repoName;
        this.projectId = projectId;
        this.versionBumperId = versionBumperId;
        this.url = url;
        this.description = description;
        this.public_ = public_;
        this.securityId = securityId;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "repo_details_id", unique = true, nullable = false, precision = 19)
    @NotNull
    public Long getRepoDetailsId() {
        return this.repoDetailsId;
    }

    public void setRepoDetailsId(Long repoDetailsId) {
        this.repoDetailsId = repoDetailsId;
    }

    @Column(name = "repo_name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getRepoName() {
        return this.repoName;
    }

    public void setRepoName(String repoName) {
        this.repoName = repoName;
    }

    @Column(name = "project_id", nullable = false, precision = 19)
    @NotNull
    public Long getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    @Column(name = "version_bumper_id", nullable = false, precision = 19)
    @NotNull
    public Long getVersionBumperId() {
        return this.versionBumperId;
    }

    public void setVersionBumperId(Long versionBumperId) {
        this.versionBumperId = versionBumperId;
    }

    @Column(name = "url", length = 65535)
    @Size(max = 65535)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "description", length = 65535)
    @Size(max = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "public", precision = 3)
    public Byte getPublic() {
        return this.public_;
    }

    public void setPublic(Byte public_) {
        this.public_ = public_;
    }

    @Column(name = "security_id", nullable = false, precision = 19)
    @NotNull
    public Long getSecurityId() {
        return this.securityId;
    }

    public void setSecurityId(Long securityId) {
        this.securityId = securityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RepoDetails (");

        sb.append(repoDetailsId);
        sb.append(", ").append(repoName);
        sb.append(", ").append(projectId);
        sb.append(", ").append(versionBumperId);
        sb.append(", ").append(url);
        sb.append(", ").append(description);
        sb.append(", ").append(public_);
        sb.append(", ").append(securityId);

        sb.append(")");
        return sb.toString();
    }
}
