/*
 * This file is generated by jOOQ.
 */
package tech.crom.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user_details", schema = "version_manager_test", indexes = {
    @Index(name = "PRIMARY", unique = true, columnList = "user_id ASC")
})
public class UserDetails implements Serializable {

    private static final long serialVersionUID = 2131742915;

    private Long   userId;
    private String userName;
    private String name;

    public UserDetails() {}

    public UserDetails(UserDetails value) {
        this.userId = value.userId;
        this.userName = value.userName;
        this.name = value.name;
    }

    public UserDetails(
        Long   userId,
        String userName,
        String name
    ) {
        this.userId = userId;
        this.userName = userName;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id", unique = true, nullable = false, precision = 19)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "user_name", nullable = false, length = 128)
    @NotNull
    @Size(max = 128)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "name", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDetails (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
