/**
 * This class is generated by jOOQ
 */
package tech.crom.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import tech.crom.db.Keys;
import tech.crom.db.VersionManagerTest;
import tech.crom.db.tables.records.AclObjectIdentityRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclObjectIdentityTable extends TableImpl<AclObjectIdentityRecord> {

    private static final long serialVersionUID = 1088936377;

    /**
     * The reference instance of <code>version_manager_test.acl_object_identity</code>
     */
    public static final AclObjectIdentityTable ACL_OBJECT_IDENTITY = new AclObjectIdentityTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AclObjectIdentityRecord> getRecordType() {
        return AclObjectIdentityRecord.class;
    }

    /**
     * The column <code>version_manager_test.acl_object_identity.id</code>.
     */
    public final TableField<AclObjectIdentityRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>version_manager_test.acl_object_identity.object_id_class</code>.
     */
    public final TableField<AclObjectIdentityRecord, ULong> OBJECT_ID_CLASS = createField("object_id_class", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>version_manager_test.acl_object_identity.object_id_identity</code>.
     */
    public final TableField<AclObjectIdentityRecord, Long> OBJECT_ID_IDENTITY = createField("object_id_identity", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>version_manager_test.acl_object_identity.parent_object</code>.
     */
    public final TableField<AclObjectIdentityRecord, ULong> PARENT_OBJECT = createField("parent_object", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>version_manager_test.acl_object_identity.owner_sid</code>.
     */
    public final TableField<AclObjectIdentityRecord, ULong> OWNER_SID = createField("owner_sid", org.jooq.impl.SQLDataType.BIGINTUNSIGNED, this, "");

    /**
     * The column <code>version_manager_test.acl_object_identity.entries_inheriting</code>.
     */
    public final TableField<AclObjectIdentityRecord, Boolean> ENTRIES_INHERITING = createField("entries_inheriting", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>version_manager_test.acl_object_identity</code> table reference
     */
    public AclObjectIdentityTable() {
        this("acl_object_identity", null);
    }

    /**
     * Create an aliased <code>version_manager_test.acl_object_identity</code> table reference
     */
    public AclObjectIdentityTable(String alias) {
        this(alias, ACL_OBJECT_IDENTITY);
    }

    private AclObjectIdentityTable(String alias, Table<AclObjectIdentityRecord> aliased) {
        this(alias, aliased, null);
    }

    private AclObjectIdentityTable(String alias, Table<AclObjectIdentityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VersionManagerTest.VERSION_MANAGER_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AclObjectIdentityRecord, ULong> getIdentity() {
        return Keys.IDENTITY_ACL_OBJECT_IDENTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AclObjectIdentityRecord> getPrimaryKey() {
        return Keys.KEY_ACL_OBJECT_IDENTITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AclObjectIdentityRecord>> getKeys() {
        return Arrays.<UniqueKey<AclObjectIdentityRecord>>asList(Keys.KEY_ACL_OBJECT_IDENTITY_PRIMARY, Keys.KEY_ACL_OBJECT_IDENTITY_UK_ACL_OBJECT_IDENTITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AclObjectIdentityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AclObjectIdentityRecord, ?>>asList(Keys.FK_ACL_OBJECT_IDENTITY_CLASS, Keys.FK_ACL_OBJECT_IDENTITY_PARENT, Keys.FK_ACL_OBJECT_IDENTITY_OWNER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AclObjectIdentityTable as(String alias) {
        return new AclObjectIdentityTable(alias, this);
    }

    /**
     * Rename this table
     */
    public AclObjectIdentityTable rename(String name) {
        return new AclObjectIdentityTable(name, null);
    }
}
