/*
 * This file is generated by jOOQ.
 */
package tech.crom.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import tech.crom.db.Indexes;
import tech.crom.db.Keys;
import tech.crom.db.VersionManagerTest;
import tech.crom.db.tables.records.WatcherRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatcherTable extends TableImpl<WatcherRecord> {

    private static final long serialVersionUID = 1726412972;

    /**
     * The reference instance of <code>version_manager_test.watcher</code>
     */
    public static final WatcherTable WATCHER = new WatcherTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WatcherRecord> getRecordType() {
        return WatcherRecord.class;
    }

    /**
     * The column <code>version_manager_test.watcher.watcher_id</code>.
     */
    public final TableField<WatcherRecord, Long> WATCHER_ID = createField("watcher_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>version_manager_test.watcher.user_id</code>.
     */
    public final TableField<WatcherRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>version_manager_test.watcher.project_detail_id</code>.
     */
    public final TableField<WatcherRecord, Long> PROJECT_DETAIL_ID = createField("project_detail_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>version_manager_test.watcher.repo_detail_id</code>.
     */
    public final TableField<WatcherRecord, Long> REPO_DETAIL_ID = createField("repo_detail_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>version_manager_test.watcher</code> table reference
     */
    public WatcherTable() {
        this(DSL.name("watcher"), null);
    }

    /**
     * Create an aliased <code>version_manager_test.watcher</code> table reference
     */
    public WatcherTable(String alias) {
        this(DSL.name(alias), WATCHER);
    }

    /**
     * Create an aliased <code>version_manager_test.watcher</code> table reference
     */
    public WatcherTable(Name alias) {
        this(alias, WATCHER);
    }

    private WatcherTable(Name alias, Table<WatcherRecord> aliased) {
        this(alias, aliased, null);
    }

    private WatcherTable(Name alias, Table<WatcherRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> WatcherTable(Table<O> child, ForeignKey<O, WatcherRecord> key) {
        super(child, key, WATCHER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return VersionManagerTest.VERSION_MANAGER_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WATCHER_PRIMARY, Indexes.WATCHER_PROJECT_DETAIL_ID, Indexes.WATCHER_REPO_DETAIL_ID, Indexes.WATCHER_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WatcherRecord, Long> getIdentity() {
        return Keys.IDENTITY_WATCHER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WatcherRecord> getPrimaryKey() {
        return Keys.KEY_WATCHER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WatcherRecord>> getKeys() {
        return Arrays.<UniqueKey<WatcherRecord>>asList(Keys.KEY_WATCHER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WatcherRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WatcherRecord, ?>>asList(Keys.WATCHER_IBFK_1, Keys.WATCHER_IBFK_2, Keys.WATCHER_IBFK_3);
    }

    public UserDetailsTable userDetails() {
        return new UserDetailsTable(this, Keys.WATCHER_IBFK_1);
    }

    public ProjectDetailsTable projectDetails() {
        return new ProjectDetailsTable(this, Keys.WATCHER_IBFK_2);
    }

    public RepoDetailsTable repoDetails() {
        return new RepoDetailsTable(this, Keys.WATCHER_IBFK_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatcherTable as(String alias) {
        return new WatcherTable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatcherTable as(Name alias) {
        return new WatcherTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WatcherTable rename(String name) {
        return new WatcherTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WatcherTable rename(Name name) {
        return new WatcherTable(name, null);
    }
}
